// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA06N5X-49bou0QdLKJPMKdpUp9RIHVpes',
    appId: '1:894321452295:web:186991e25786e89ecb91a2',
    messagingSenderId: '894321452295',
    projectId: 'garage-337f8',
    authDomain: 'garage-337f8.firebaseapp.com',
    storageBucket: 'garage-337f8.appspot.com',
    measurementId: 'G-394K5F6DLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtPwc-JvLkxKmJOsIOI4d9sHi6uyFdg4s',
    appId: '1:894321452295:android:8e3c1d2b95069661cb91a2',
    messagingSenderId: '894321452295',
    projectId: 'garage-337f8',
    storageBucket: 'garage-337f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb3AW3rg1DZbky_zCsInc6xJ1hKWG6JXc',
    appId: '1:894321452295:ios:41a17f601d301230cb91a2',
    messagingSenderId: '894321452295',
    projectId: 'garage-337f8',
    storageBucket: 'garage-337f8.appspot.com',
    iosBundleId: 'com.example.fusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb3AW3rg1DZbky_zCsInc6xJ1hKWG6JXc',
    appId: '1:894321452295:ios:41a17f601d301230cb91a2',
    messagingSenderId: '894321452295',
    projectId: 'garage-337f8',
    storageBucket: 'garage-337f8.appspot.com',
    iosBundleId: 'com.example.fusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnBtHqKUosYBBdR4NCJ8ox8AxuduhwUt0',
    appId: '1:894321452295:web:f8888aed62143d9ccb91a2',
    messagingSenderId: '894321452295',
    projectId: 'garage-337f8',
    authDomain: 'garage-337f8.firebaseapp.com',
    storageBucket: 'garage-337f8.appspot.com',
    measurementId: 'G-5H330S04K9',
  );
}
